relativeurls = true
baseurl = "https://pat-s.github.io/"
title = "Patrick Schratz"
copyright = "&copy; 2017 Patrick Schratz"
theme = "academic"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "<sup>^</sup>"

# Syntax Highlighting
# PygmentsCodeFences = true
# pygmentsstyle = "monokai"

## Link custom CSS and JS assets (not needed currently as highlighting is supported by default now)
#custom_js = ["highlight.pack.js"]
#custom_css = ["dracula.css", "my-hugo-academic.css"]

#   For more info on the highlighting options, see:
#   https://sourcethemes.com/academic/post/writing-markdown-latex/#highlighting-options
highlight = true
highlight_languages = ["r"]
highlight_style = "dracula"

# old approach
#highlight = true
#highlight_languages = ["r"]

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-35704082-2"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[params]
  name = "Patrick Schratz"
  role = "PhD Student"
  organization = "Friedrich-Schiller-University Jena"
  avatar = "avatar.jpg"
  email = "patrick.schratz@uni-jena.de"
  address = "Grietgasse 6, Room 126, 07745 Jena (Germany)"
  office_hours = "Monday - Friday: 9:00 to 18:00"
  phone = "+49-3641-9-48973"
  skype = ""
  telegram = ""

  # Color theme.
  #   Choose from `default`, `ocean`, `forest`, or `coffee`.
  color_theme = "defaul"

  # Font style.
  #   Choose from `default`, `classic`, or `playfair`.
  font = "default"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Diplay a logo in navigation bar rather than title (optional).
  #   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
  logo = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:patrick.schratz@uni-jena.de"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "https://www.linkedin.com/in/patrick-schratz-94666b101?trk=hp-identity-name"

  [[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "https://www.researchgate.net/profile/Patrick_Schratz"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/pjs_228"

  # [[params.social]]
  #  icon = "google-scholar"
  #  icon_pack = "ai"
  #  link = "https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/pat-s"

  [[params.social]]
    icon = "stack-exchange"
    icon_pack = "fa"
    link = "http://stackexchange.com/users/5237716/pat-s?tab=accounts"



# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 4

[[menu.main]]
  name = "Rec. Reading"
  url = "#recommended_reading"
  weight = 4.5

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 2

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6


# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
